-- Enable RLS
alter table public.jobs enable row level security;

-- Jobs policies: user can select/insert their rows; user cannot update; service role can update (bypasses RLS)
drop policy if exists jobs_select_own on public.jobs;
create policy jobs_select_own on public.jobs
  for select
  to authenticated
  using (user_id = auth.uid());

drop policy if exists jobs_insert_own on public.jobs;
create policy jobs_insert_own on public.jobs
  for insert
  to authenticated
  with check (user_id = auth.uid());

-- No update policy for authenticated users (they cannot update). Service role bypasses RLS and can update.

-- Storage policies to enforce folder-per-user key prefix
-- Helper: the user folder is the first path segment before '/'

-- room_inputs: allow authenticated users to insert/update/delete only within their own {user_id}/ prefix
drop policy if exists room_inputs_insert_own on storage.objects;
create policy room_inputs_insert_own on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'room_inputs'
    and split_part(name, '/', 1) = auth.uid()::text
  );

drop policy if exists room_inputs_update_own on storage.objects;
create policy room_inputs_update_own on storage.objects
  for update to authenticated
  using (
    bucket_id = 'room_inputs'
    and split_part(name, '/', 1) = auth.uid()::text
  )
  with check (
    bucket_id = 'room_inputs'
    and split_part(name, '/', 1) = auth.uid()::text
  );

drop policy if exists room_inputs_delete_own on storage.objects;
create policy room_inputs_delete_own on storage.objects
  for delete to authenticated
  using (
    bucket_id = 'room_inputs'
    and split_part(name, '/', 1) = auth.uid()::text
  );

-- room_outputs: end-users should not insert. Only service role should write (bypasses RLS). Optionally allow select via signed URLs only.
-- We omit select/update/delete policies for room_outputs for authenticated users to keep it private; signed URLs are generated by backend.

